### ISSUE TITLE
Look into FOC for TalonFx

### ISSUE THREAD

**Issue by ingensargens** [team6749/2024-Crescendo-V2#6]
https://pro.docs.ctr-electronics.com/en/stable/docs/api-reference/device-specific/talonfx/talonfx-control-intro.html#field-oriented-control

Not sure if this is useful or means anything but TalonFx Implements Field Oriented Control

**Comment by ingensargens** [comment]
Not applicable to us

**Comment by mootw** [comment]
its actually crazy u have to pay for that. its literally a software update
